In [2]:
import numpy as np
from numpy.random import randn
np.set_printoptions(precision=2)
array=np.array([1,2,3,4,5,6])
b=np.array([[10,20,30],[40,50,60]])
#creating arrays via assignment;randn function generates positive as well as negative number
np.random.seed(25)
c=36*np.random.randn(6)
print(c)

[  8.22  36.97 -30.23 -21.28 -34.45  -8.  ]


In [6]:
d=np.arange(1,35)
print(d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34]


In [8]:
array*10

array([10, 20, 30, 40, 50, 60])

In [9]:
#multiplying matrices and basic linear algebra
a=np.array([[2,4,6],[1,3,5],[5,8,9]])
print(a)

[[2 4 6]
 [1 3 5]
 [5 8 9]]


In [10]:
bbb=np.array([[1,4,5],[3,5,6],[9,6,7]])
print(bbb)

[[1 4 5]
 [3 5 6]
 [9 6 7]]


In [11]:
c=a*bbb
print(c)

[[ 2 16 30]
 [ 3 15 30]
 [45 48 63]]


In [12]:
#matrix multiplication or dot product
np.dot(a,bbb)

array([[ 68,  64,  76],
       [ 55,  49,  58],
       [110, 114, 136]])

In [ ]:
#matrix multiplication or dot product
